// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    public partial class ApplicationRoleClaim : IdentityRoleClaim<string>
    {

        public ApplicationRole ApplicationRole { get; set; }
    }

}
// </auto-generated>
