// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    /// <summary>
    /// 使用者登入紀錄
    /// </summary>
    public partial class ApplicationUserClaim : IdentityUserClaim<string>
    {

        public ApplicationUser ApplicationUser { get; set; }
    }

}
// </auto-generated>
