// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    public partial class ApplicationUserToken : IdentityUserToken<string>
    {

        public ApplicationUser ApplicationUser { get; set; }
    }

}
// </auto-generated>
