// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    /// <summary>
    /// 使用者
    /// </summary>
    public partial class ApplicationUser : IdentityUser
    {
        /// <summary>
        /// 組織機關ID
        /// </summary>
        public Guid? OrgId { get; set; }

        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        /// <summary>
        /// 是否啟用
        /// </summary>
        public bool IsEnabled { get; set; } = true;

        /// <summary>
        /// 中文姓名
        /// </summary>
        public string FullName { get; set; } = string.Empty;

        /// <summary>
        /// APP註冊驗證碼
        /// </summary>
        public string? RegisterVerifyCode { get; set; }

        /// <summary>
        /// 註冊驗證完成
        /// </summary>
        public bool IsRegisterVerify { get; set; } = false;

        /// <summary>
        /// 是否執行重設密碼
        /// </summary>
        public bool IsForgotPwd { get; set; } = false;

        /// <summary>
        /// 忘記密碼驗證碼
        /// </summary>
        public string? ForgotPwdVerifyCode { get; set; }

        /// <summary>
        /// 上次修改密碼時間(Null:代表一進入就要強制更新，有時間大於3個月也是要強制更新)
        /// </summary>
        public DateTime LastChangeQoo { get; set; } = DateTime.Now;

        /// <summary>
        /// 必須先修改密碼才能進入系統
        /// </summary>
        public bool MustChangeQoo { get; set; } = true;

        /// <summary>
        /// 性別 1:男, 0:女
        /// </summary>
        public bool Gender { get; set; } = true;

        /// <summary>
        /// 生日
        /// </summary>
        public DateTime? Birthday { get; set; }

        /// <summary>
        /// 職稱
        /// </summary>
        public string? JobTitle { get; set; }

        /// <summary>
        /// 聯絡電話
        /// </summary>
        public string? Tel { get; set; }

        /// <summary>
        /// 上次登入時間
        /// </summary>
        public DateTime? LastLogin { get; set; }

        /// <summary>
        /// 登入次數
        /// </summary>
        public int LoginTimes { get; set; } = 0;

        /// <summary>
        /// 啟用 OTP 登入
        /// </summary>
        public bool UseOtp { get; set; } = false;

        /// <summary>
        /// OTP 驗證碼
        /// </summary>
        public string? OtpSecret { get; set; }

        /// <summary>
        /// 電話分機
        /// </summary>
        public string? TelExt { get; set; }

        /// <summary>
        /// 登入方式:0=帳密登入、1=府內單登
        /// </summary>
        public LoginType LoginType { get; set; } = (LoginType) 0;

        /// <summary>
        /// 帳號是否刪除
        /// </summary>
        public bool IsDelete { get; set; } = false;

        /// <summary>
        /// LDAP 專有名稱
        /// </summary>
        public string? DistinguishedName { get; set; }

        // Reverse navigation
        public ICollection<AiProject> AiProjects { get; set; } = new List<AiProject>();
        public ICollection<ApplicationRole> ApplicationRoles { get; set; } = new List<ApplicationRole>();
        public ICollection<ApplicationUserClaim> ApplicationUserClaims { get; set; } = new List<ApplicationUserClaim>();
        public ICollection<ApplicationUserLogin> ApplicationUserLogins { get; set; } = new List<ApplicationUserLogin>();
        public ICollection<ApplicationUserToken> ApplicationUserTokens { get; set; } = new List<ApplicationUserToken>();
        public ICollection<LlmInfo> LlmInfoes { get; set; } = new List<LlmInfo>();
        public ICollection<McpServer> McpServers { get; set; } = new List<McpServer>();
        public ICollection<UserFootprint> UserFootprints { get; set; } = new List<UserFootprint>();

        public Organization Organization { get; set; }
    }

}
// </auto-generated>
