// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    /// <summary>
    /// Captcha
    /// </summary>
    public partial class Captcha : AuditableEntity
    {
        /// <summary>
        /// Captcha ID
        /// </summary>
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Captcha Code
        /// </summary>
        public string Code { get; set; } = string.Empty;
    }

}
// </auto-generated>
