// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    public partial class Filex : AuditableEntity
    {
        /// <summary>
        /// 檔案唯一Id
        /// </summary>
        public Guid FileId { get; set; } = Guid.NewGuid();

        /// <summary>
        /// 檔案名稱
        /// </summary>
        public string FileName { get; set; } = string.Empty;

        /// <summary>
        /// 副檔名
        /// </summary>
        public string Extension { get; set; } = string.Empty;

        /// <summary>
        /// 檔案大小
        /// </summary>
        public long Size { get; set; }

        /// <summary>
        /// 檔案類型
        /// </summary>
        public string ContentType { get; set; } = string.Empty;

        /// <summary>
        /// 備註
        /// </summary>
        public string? Note { get; set; }

        /// <summary>
        /// 流水號
        /// </summary>
        public int FileSeq { get; set; }
    }

}
// </auto-generated>
