// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    public partial class LlmInfo : AuditableEntity
    {
        /// <summary>
        /// LLM ID
        /// </summary>
        public Guid LlmId { get; set; } = Guid.NewGuid();

        /// <summary>
        /// 擁有者 UserId
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// 模型管理名稱、服務識別碼
        /// </summary>
        public string ServiceId { get; set; } = string.Empty;

        /// <summary>
        /// LLM 模型名稱，gpt-4o
        /// </summary>
        public string ModelId { get; set; } = string.Empty;

        /// <summary>
        /// LLM 來源類型，0:OpenAi,1:AzureOpenAi,2:Ollama,3:Gemini,4:Afs
        /// </summary>
        public LlmSourceType LlmSourceType { get; set; } = (LlmSourceType) 0;

        /// <summary>
        /// API 金鑰
        /// </summary>
        public string? ApiKey { get; set; }

        /// <summary>
        /// 端點網址
        /// </summary>
        public string? Endpoint { get; set; }

        /// <summary>
        /// 部署名稱
        /// </summary>
        public string? DeploymentName { get; set; }

        /// <summary>
        /// 說明
        /// </summary>
        public string? Description { get; set; }

        // Reverse navigation
        public ICollection<AiProject> AiProjects { get; set; } = new List<AiProject>();

        public ApplicationUser ApplicationUser { get; set; }
    }

}
// </auto-generated>
