// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    public partial class McpServer : AuditableEntity
    {
        /// <summary>
        /// MCP Server ID
        /// </summary>
        public Guid McpServerId { get; set; } = Guid.NewGuid();

        /// <summary>
        /// 擁有者 UserId
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// MCP 服務名稱，只能是英數字以及底線
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// MCP 伺服器通訊型態，0:Stdio,1:Sse
        /// </summary>
        public McpServerType McpServerType { get; set; } = (McpServerType) 0;

        /// <summary>
        /// 伺服器的 SSE 端點 URL
        /// </summary>
        public string? SseUrl { get; set; }

        /// <summary>
        /// stdio 的指令
        /// </summary>
        public string? StdioCommand { get; set; }

        /// <summary>
        /// stdio 指令參數，存 JSON array
        /// </summary>
        public string? StdioArgs { get; set; }

        /// <summary>
        /// stdio 環境變數，存 JSON object
        /// </summary>
        public string? StdioEnv { get; set; }

        /// <summary>
        /// 工具清單，存 JSON object，Name、Description
        /// </summary>
        public string Tools { get; set; } = string.Empty;

        // Reverse navigation
        public ICollection<AiProject> AiProjects { get; set; } = new List<AiProject>();

        public ApplicationUser ApplicationUser { get; set; }
    }

}
// </auto-generated>
