// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    public partial class Organization : AuditableEntity
    {
        /// <summary>
        /// 組織單位編號
        /// </summary>
        public Guid OrgId { get; set; } = Guid.NewGuid();

        /// <summary>
        /// 組織單位名稱
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// 組織簡稱
        /// </summary>
        public string? NameShort { get; set; }

        /// <summary>
        /// 上層組織
        /// </summary>
        public Guid? Upper { get; set; }

        // Reverse navigation
        public ICollection<ApplicationUser> ApplicationUsers { get; set; } = new List<ApplicationUser>();
        public ICollection<Organization> Organizations { get; set; } = new List<Organization>();

        public Organization OrganizationUpper { get; set; }
    }

}
// </auto-generated>
