// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    /// <summary>
    /// 使用者足跡，自動記錄
    /// </summary>
    public partial class UserFootprint
    {
        /// <summary>
        /// 使用者足跡 SEQ
        /// </summary>
        public int Seq { get; set; }

        /// <summary>
        /// 使用者ID
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// 帳號ID
        /// </summary>
        public string Auth { get; set; } = string.Empty;

        /// <summary>
        /// 操作紀錄類型：API、MVC、SQL
        /// </summary>
        public string LogType { get; set; } = "API";

        /// <summary>
        /// 操作路徑，可與 swagger json 配對
        /// </summary>
        public string Url { get; set; } = string.Empty;

        /// <summary>
        /// HTTP動詞
        /// </summary>
        public string HttpVerb { get; set; } = "GET";

        /// <summary>
        /// GET 查詢參數
        /// </summary>
        public string QueryString { get; set; } = string.Empty;

        /// <summary>
        /// POST 資料內容
        /// </summary>
        public string PostBody { get; set; } = string.Empty;

        /// <summary>
        /// 使用者代理資訊：作業系統、瀏覽器
        /// </summary>
        public string UserAgent { get; set; } = string.Empty;

        /// <summary>
        /// IP
        /// </summary>
        public string Ip { get; set; } = string.Empty;

        /// <summary>
        /// 操作時間
        /// </summary>
        public DateTime RequestTime { get; set; } = DateTime.Now;

        /// <summary>
        /// Controller 名稱
        /// </summary>
        public string? Controller { get; set; }

        /// <summary>
        /// Action 名稱
        /// </summary>
        public string? Action { get; set; }

        /// <summary>
        /// 頁面名稱 / 操作項目
        /// </summary>
        public string? PageName { get; set; }

        /// <summary>
        /// 瀏覽器類型、版本
        /// </summary>
        public string? Browser { get; set; }

        /// <summary>
        /// 作業平台
        /// </summary>
        public string? Os { get; set; }

        public ApplicationUser ApplicationUser { get; set; }
    }

}
// </auto-generated>
