// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    /// <summary>
    /// 使用者帳號修改歷程
    /// </summary>
    public partial class UserHistory
    {
        /// <summary>
        /// 歷程流水號
        /// </summary>
        public int HistorySeq { get; set; }

        /// <summary>
        /// 使用者ID
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// 登入者或操作者ID
        /// </summary>
        public string? LoginId { get; set; }

        /// <summary>
        /// 使用者資料異動類型
        /// </summary>
        public UserHistoryType UserHistoryType { get; set; } = (UserHistoryType) 0;

        /// <summary>
        /// 資料異動類型名稱
        /// </summary>
        public string HistoryTypeName { get; set; } = string.Empty;

        /// <summary>
        /// 操作時間
        /// </summary>
        public DateTime RequestTime { get; set; } = DateTime.Now;

        /// <summary>
        /// 操作執行結果是否成功
        /// </summary>
        public bool RequestResult { get; set; } = false;

        /// <summary>
        /// 操作結果額外資訊
        /// </summary>
        public string? Message { get; set; }

        /// <summary>
        /// IP
        /// </summary>
        public string Ip { get; set; } = "-";
    }

}
// </auto-generated>
