// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    /// <summary>
    /// 使用者密碼變更歷程
    /// </summary>
    public partial class UserQooHistory
    {
        /// <summary>
        /// 歷程流水號
        /// </summary>
        public int HistorySeq { get; set; }

        /// <summary>
        /// 使用者ID
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// 登入者或操作者ID
        /// </summary>
        public string LoginId { get; set; } = string.Empty;

        /// <summary>
        /// 操作時間
        /// </summary>
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        /// <summary>
        /// 加密後的密碼
        /// </summary>
        public string? QooHash { get; set; }
    }

}
// </auto-generated>
