// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    /// <summary>
    /// 使用者 Token 紀錄
    /// </summary>
    public partial class UserTokenx
    {
        /// <summary>
        /// 使用者 Token 紀錄 ID
        /// </summary>
        public Guid TokenId { get; set; }

        /// <summary>
        /// 使用者ID
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// 帳號
        /// </summary>
        public string UserName { get; set; } = string.Empty;

        /// <summary>
        /// Access Token
        /// </summary>
        public string AccessToken { get; set; } = string.Empty;

        /// <summary>
        /// Refresh Token
        /// </summary>
        public string ReFreshToken { get; set; } = string.Empty;

        /// <summary>
        /// Refresh Token 到期日
        /// </summary>
        public DateTime ExpiredDate { get; set; }

        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        /// <summary>
        /// 每次 Refresh 後需要撤銷
        /// </summary>
        public bool IsEnabled { get; set; } = true;
    }

}
// </auto-generated>
