// <auto-generated>
#nullable enable

namespace Geo.Smart.AiAgentHub.DataAccess.Entities
{
    /// <summary>
    /// 強制變更密碼
    /// </summary>
    public partial class VerifyCode
    {
        /// <summary>
        /// 強制變更密碼id
        /// </summary>
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// 使用者Id
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// 有效起日
        /// </summary>
        public DateTime StartTime { get; set; }

        /// <summary>
        /// 有效迄日
        /// </summary>
        public DateTime EndTime { get; set; }

        /// <summary>
        /// 驗證類型(1:信箱註冊、2:第一次登入、3:三個月強制變更密碼、4:忘記密碼)
        /// </summary>
        public VerifyType VerifyType { get; set; }
    }

}
// </auto-generated>
