// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class AiProjectConfiguration : IEntityTypeConfiguration<AiProject>
    {
        public void Configure(EntityTypeBuilder<AiProject> builder)
        {
            builder.ToTable("AiProject", "dbo");
            builder.HasKey(x => x.ProjectId).HasName("PK_AiProject").IsClustered();

            builder.Property(x => x.ProjectId).HasColumnName(@"ProjectId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.SystemPrompt).HasColumnName(@"SystemPrompt").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
            builder.Property(x => x.Temperature).HasColumnName(@"Temperature").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.TopP).HasColumnName(@"TopP").HasColumnType("float").HasPrecision(53).IsRequired(false);
            builder.Property(x => x.TopK).HasColumnName(@"TopK").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.MaxTokens).HasColumnName(@"MaxTokens").HasColumnType("int").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.ApplicationUser).WithMany(b => b.AiProjects).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AiProject_AspNetUsers");
        }
    }

}
// </auto-generated>
