// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class ApplicationUserTokenConfiguration : IEntityTypeConfiguration<ApplicationUserToken>
    {
        public void Configure(EntityTypeBuilder<ApplicationUserToken> builder)
        {
            builder.ToTable("AspNetUserTokens", "dbo");
            builder.HasKey(x => new { x.UserId, x.LoginProvider, x.Name }).HasName("PK_AspNetUserTokens").IsClustered();

            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128).ValueGeneratedNever();
            builder.Property(x => x.LoginProvider).HasColumnName(@"LoginProvider").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128).ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128).ValueGeneratedNever();
            builder.Property(x => x.Value).HasColumnName(@"Value").HasColumnType("nvarchar(max)").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.ApplicationUser).WithMany(b => b.ApplicationUserTokens).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AspNetUserTokens_AspNetUsers");
        }
    }

}
// </auto-generated>
