// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class ApplicationUserLoginConfiguration : IEntityTypeConfiguration<ApplicationUserLogin>
    {
        public void Configure(EntityTypeBuilder<ApplicationUserLogin> builder)
        {
            builder.ToTable("AspNetUserLogins", "dbo");
            builder.HasKey(x => new { x.LoginProvider, x.ProviderKey, x.UserId }).HasName("PK_dbo.AspNetUserLogins").IsClustered();

            builder.Property(x => x.LoginProvider).HasColumnName(@"LoginProvider").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128).ValueGeneratedNever();
            builder.Property(x => x.ProviderKey).HasColumnName(@"ProviderKey").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128).ValueGeneratedNever();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128).ValueGeneratedNever();
            builder.Property(x => x.ProviderDisplayName).HasColumnName(@"ProviderDisplayName").HasColumnType("nvarchar(max)").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.ApplicationUser).WithMany(b => b.ApplicationUserLogins).HasForeignKey(c => c.UserId).HasConstraintName("FK_dbo.AspNetUserLogins_dbo.AspNetUsers_UserId");
        }
    }

}
// </auto-generated>
