// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class ApplicationUserConfiguration : IEntityTypeConfiguration<ApplicationUser>
    {
        public void Configure(EntityTypeBuilder<ApplicationUser> builder)
        {
            builder.ToTable("AspNetUsers", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.AspNetUsers").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128).ValueGeneratedNever();
            builder.Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar(256)").IsRequired(false).HasMaxLength(256);
            builder.Property(x => x.NormalizedUserName).HasColumnName(@"NormalizedUserName").HasColumnType("nvarchar(256)").IsRequired(false).HasMaxLength(256);
            builder.Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar(256)").IsRequired(false).HasMaxLength(256);
            builder.Property(x => x.NormalizedEmail).HasColumnName(@"NormalizedEmail").HasColumnType("nvarchar(256)").IsRequired(false).HasMaxLength(256);
            builder.Property(x => x.EmailConfirmed).HasColumnName(@"EmailConfirmed").HasColumnType("bit").IsRequired();
            builder.Property(x => x.PasswordHash).HasColumnName(@"PasswordHash").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.SecurityStamp).HasColumnName(@"SecurityStamp").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.PhoneNumber).HasColumnName(@"PhoneNumber").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.PhoneNumberConfirmed).HasColumnName(@"PhoneNumberConfirmed").HasColumnType("bit").IsRequired();
            builder.Property(x => x.TwoFactorEnabled).HasColumnName(@"TwoFactorEnabled").HasColumnType("bit").IsRequired();
            builder.Property(x => x.LockoutEnd).HasColumnName(@"LockoutEnd").HasColumnType("datetimeoffset").IsRequired(false);
            builder.Property(x => x.LockoutEnabled).HasColumnName(@"LockoutEnabled").HasColumnType("bit").IsRequired();
            builder.Property(x => x.AccessFailedCount).HasColumnName(@"AccessFailedCount").HasColumnType("int").IsRequired();
            builder.Property(x => x.OrgId).HasColumnName(@"OrgId").HasColumnType("uniqueidentifier").IsRequired(false);
            builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
            builder.Property(x => x.FullName).HasColumnName(@"FullName").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.RegisterVerifyCode).HasColumnName(@"RegisterVerifyCode").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.IsRegisterVerify).HasColumnName(@"IsRegisterVerify").HasColumnType("bit").IsRequired();
            builder.Property(x => x.IsForgotPwd).HasColumnName(@"IsForgotPwd").HasColumnType("bit").IsRequired();
            builder.Property(x => x.ForgotPwdVerifyCode).HasColumnName(@"ForgotPwdVerifyCode").HasColumnType("varchar(10)").IsRequired(false).IsUnicode(false).HasMaxLength(10);
            builder.Property(x => x.LastChangeQoo).HasColumnName(@"LastChangeQoo").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.MustChangeQoo).HasColumnName(@"MustChangeQoo").HasColumnType("bit").IsRequired();
            builder.Property(x => x.Gender).HasColumnName(@"Gender").HasColumnType("bit").IsRequired();
            builder.Property(x => x.Birthday).HasColumnName(@"Birthday").HasColumnType("date").IsRequired(false);
            builder.Property(x => x.JobTitle).HasColumnName(@"JobTitle").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Tel).HasColumnName(@"Tel").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.LastLogin).HasColumnName(@"LastLogin").HasColumnType("datetime").IsRequired(false);
            builder.Property(x => x.LoginTimes).HasColumnName(@"LoginTimes").HasColumnType("int").IsRequired();
            builder.Property(x => x.UseOtp).HasColumnName(@"UseOtp").HasColumnType("bit").IsRequired();
            builder.Property(x => x.OtpSecret).HasColumnName(@"OtpSecret").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.TelExt).HasColumnName(@"TelExt").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.LoginType).HasColumnName(@"LoginType").HasColumnType("int").IsRequired();
            builder.Property(x => x.IsDelete).HasColumnName(@"IsDelete").HasColumnType("bit").IsRequired();
            builder.Property(x => x.DistinguishedName).HasColumnName(@"DistinguishedName").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);

            // Foreign keys
            builder.HasOne(a => a.Organization).WithMany(b => b.ApplicationUsers).HasForeignKey(c => c.OrgId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_AspNetUsers_Organization");
        }
    }

}
// </auto-generated>
