// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class ApplicationRoleConfiguration : IEntityTypeConfiguration<ApplicationRole>
    {
        public void Configure(EntityTypeBuilder<ApplicationRole> builder)
        {
            builder.ToTable("AspNetRoles", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.AspNetRoles").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128).ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(256)").IsRequired(false).HasMaxLength(256);
            builder.Property(x => x.NormalizedName).HasColumnName(@"NormalizedName").HasColumnType("nvarchar(256)").IsRequired(false).HasMaxLength(256);
            builder.Property(x => x.ConcurrencyStamp).HasColumnName(@"ConcurrencyStamp").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.HasMany<ApplicationUser>(t => t.ApplicationUsers).WithMany(t => t.ApplicationRoles).UsingEntity<Dictionary<string, object>>("AspNetUserRoles",
                    j => j.HasOne<ApplicationUser>().WithMany().HasForeignKey("UserId"),
                    j => j.HasOne<ApplicationRole>().WithMany().HasForeignKey("RoleId"),
                    j => j.ToTable("AspNetUserRoles", "dbo"));
        }
    }

}
// </auto-generated>
