// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class CaptchaConfiguration : IEntityTypeConfiguration<Captcha>
    {
        public void Configure(EntityTypeBuilder<Captcha> builder)
        {
            builder.ToTable("Captcha", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_Captcha").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Code).HasColumnName(@"Code").HasColumnType("varchar(6)").IsRequired().IsUnicode(false).HasMaxLength(6);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
