// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class FilexConfiguration : IEntityTypeConfiguration<Filex>
    {
        public void Configure(EntityTypeBuilder<Filex> builder)
        {
            builder.ToTable("Files", "dbo");
            builder.HasKey(x => x.FileId).HasName("PK_Files");

            builder.Property(x => x.FileId).HasColumnName(@"FileId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.FileName).HasColumnName(@"FileName").HasColumnType("nvarchar(250)").IsRequired().HasMaxLength(250);
            builder.Property(x => x.Extension).HasColumnName(@"Extension").HasColumnType("nvarchar(10)").IsRequired().HasMaxLength(10);
            builder.Property(x => x.Size).HasColumnName(@"Size").HasColumnType("bigint").IsRequired();
            builder.Property(x => x.ContentType).HasColumnName(@"ContentType").HasColumnType("nvarchar(250)").IsRequired().HasMaxLength(250);
            builder.Property(x => x.Note).HasColumnName(@"Note").HasColumnType("nvarchar(250)").IsRequired(false).HasMaxLength(250);
            builder.Property(x => x.FileSeq).HasColumnName(@"FileSeq").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();

            builder.HasIndex(x => x.FileId).HasDatabaseName("IX_Files_Seq").IsUnique();
        }
    }

}
// </auto-generated>
