// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class LlmInfoConfiguration : IEntityTypeConfiguration<LlmInfo>
    {
        public void Configure(EntityTypeBuilder<LlmInfo> builder)
        {
            builder.ToTable("LlmInfo", "dbo");
            builder.HasKey(x => x.LlmId).HasName("PK_LlmInfo").IsClustered();

            builder.Property(x => x.LlmId).HasColumnName(@"LlmId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.ServiceId).HasColumnName(@"ServiceId").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.ModelId).HasColumnName(@"ModelId").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.LlmSourceType).HasColumnName(@"LlmSourceType").HasColumnType("int").IsRequired();
            builder.Property(x => x.ApiKey).HasColumnName(@"ApiKey").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Endpoint).HasColumnName(@"Endpoint").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.DeploymentName).HasColumnName(@"DeploymentName").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar(500)").IsRequired(false).HasMaxLength(500);
            builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.ApplicationUser).WithMany(b => b.LlmInfoes).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_LlmInfo_AspNetUsers");
            builder.HasMany<AiProject>(t => t.AiProjects).WithMany(t => t.LlmInfoes).UsingEntity<Dictionary<string, object>>("RelProjectLlm",
                    j => j.HasOne<AiProject>().WithMany().HasForeignKey("ProjectId"),
                    j => j.HasOne<LlmInfo>().WithMany().HasForeignKey("LlmId"),
                    j => j.ToTable("RelProjectLlm", "dbo"));
        }
    }

}
// </auto-generated>
