// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class McpServerConfiguration : IEntityTypeConfiguration<McpServer>
    {
        public void Configure(EntityTypeBuilder<McpServer> builder)
        {
            builder.ToTable("McpServer", "dbo");
            builder.HasKey(x => x.McpServerId).HasName("PK_McpServer").IsClustered();

            builder.Property(x => x.McpServerId).HasColumnName(@"McpServerId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.McpServerType).HasColumnName(@"McpServerType").HasColumnType("int").IsRequired();
            builder.Property(x => x.SseUrl).HasColumnName(@"SseUrl").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200);
            builder.Property(x => x.StdioCommand).HasColumnName(@"StdioCommand").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.StdioArgs).HasColumnName(@"StdioArgs").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.StdioEnv).HasColumnName(@"StdioEnv").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Tools).HasColumnName(@"Tools").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.ApplicationUser).WithMany(b => b.McpServers).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_McpServer_AspNetUsers");
            builder.HasMany<AiProject>(t => t.AiProjects).WithMany(t => t.McpServers).UsingEntity<Dictionary<string, object>>("RelProjectMcp",
                    j => j.HasOne<AiProject>().WithMany().HasForeignKey("ProjectId"),
                    j => j.HasOne<McpServer>().WithMany().HasForeignKey("McpServerId"),
                    j => j.ToTable("RelProjectMcp", "dbo"));
        }
    }

}
// </auto-generated>
