// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class OrganizationConfiguration : IEntityTypeConfiguration<Organization>
    {
        public void Configure(EntityTypeBuilder<Organization> builder)
        {
            builder.ToTable("Organization", "dbo");
            builder.HasKey(x => x.OrgId).HasName("PK_ORGANIZATION").IsClustered();

            builder.Property(x => x.OrgId).HasColumnName(@"OrgId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.NameShort).HasColumnName(@"NameShort").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Upper).HasColumnName(@"Upper").HasColumnType("uniqueidentifier").IsRequired(false);
            builder.Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.OrganizationUpper).WithMany(b => b.Organizations).HasForeignKey(c => c.Upper).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_Organization_Organization");
        }
    }

}
// </auto-generated>
