// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class UserHistoryConfiguration : IEntityTypeConfiguration<UserHistory>
    {
        public void Configure(EntityTypeBuilder<UserHistory> builder)
        {
            builder.ToTable("UserHistory", "dbo");
            builder.HasKey(x => x.HistorySeq).HasName("PK_UserHistory").IsClustered();

            builder.Property(x => x.HistorySeq).HasColumnName(@"HistorySeq").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.LoginId).HasColumnName(@"LoginId").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.UserHistoryType).HasColumnName(@"UserHistoryType").HasColumnType("int").IsRequired();
            builder.Property(x => x.HistoryTypeName).HasColumnName(@"HistoryTypeName").HasColumnType("nvarchar(10)").IsRequired().HasMaxLength(10);
            builder.Property(x => x.RequestTime).HasColumnName(@"RequestTime").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.RequestResult).HasColumnName(@"RequestResult").HasColumnType("bit").IsRequired();
            builder.Property(x => x.Message).HasColumnName(@"Message").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Ip).HasColumnName(@"Ip").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
        }
    }

}
// </auto-generated>
