// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class UserFootprintConfiguration : IEntityTypeConfiguration<UserFootprint>
    {
        public void Configure(EntityTypeBuilder<UserFootprint> builder)
        {
            builder.ToTable("UserFootprint", "dbo");
            builder.HasKey(x => x.Seq).HasName("PK_UserFootprint").IsClustered();

            builder.Property(x => x.Seq).HasColumnName(@"Seq").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.Auth).HasColumnName(@"Auth").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.LogType).HasColumnName(@"LogType").HasColumnType("nvarchar(10)").IsRequired().HasMaxLength(10);
            builder.Property(x => x.Url).HasColumnName(@"Url").HasColumnType("nvarchar(500)").IsRequired().HasMaxLength(500);
            builder.Property(x => x.HttpVerb).HasColumnName(@"HttpVerb").HasColumnType("nvarchar(10)").IsRequired().HasMaxLength(10);
            builder.Property(x => x.QueryString).HasColumnName(@"QueryString").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.PostBody).HasColumnName(@"PostBody").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.UserAgent).HasColumnName(@"UserAgent").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.Ip).HasColumnName(@"Ip").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
            builder.Property(x => x.RequestTime).HasColumnName(@"RequestTime").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.Controller).HasColumnName(@"Controller").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.Action).HasColumnName(@"Action").HasColumnType("nvarchar(50)").IsRequired(false).HasMaxLength(50);
            builder.Property(x => x.PageName).HasColumnName(@"PageName").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);
            builder.Property(x => x.Browser).HasColumnName(@"Browser").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200);
            builder.Property(x => x.Os).HasColumnName(@"Os").HasColumnType("nvarchar(100)").IsRequired(false).HasMaxLength(100);

            // Foreign keys
            builder.HasOne(a => a.ApplicationUser).WithMany(b => b.UserFootprints).HasForeignKey(c => c.UserId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_UserFootprint_AspNetUsers");
        }
    }

}
// </auto-generated>
