// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class UserTokenxConfiguration : IEntityTypeConfiguration<UserTokenx>
    {
        public void Configure(EntityTypeBuilder<UserTokenx> builder)
        {
            builder.ToTable("UserToken", "dbo");
            builder.HasKey(x => x.TokenId).HasName("PK_UserToken").IsClustered();

            builder.Property(x => x.TokenId).HasColumnName(@"TokenId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar(256)").IsRequired().HasMaxLength(256);
            builder.Property(x => x.AccessToken).HasColumnName(@"AccessToken").HasColumnType("varchar(1000)").IsRequired().IsUnicode(false).HasMaxLength(1000);
            builder.Property(x => x.ReFreshToken).HasColumnName(@"ReFreshToken").HasColumnType("varchar(32)").IsRequired().IsUnicode(false).HasMaxLength(32);
            builder.Property(x => x.ExpiredDate).HasColumnName(@"ExpiredDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
