// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class UserQooHistoryConfiguration : IEntityTypeConfiguration<UserQooHistory>
    {
        public void Configure(EntityTypeBuilder<UserQooHistory> builder)
        {
            builder.ToTable("UserQooHistory", "dbo");
            builder.HasKey(x => x.HistorySeq).HasName("PK_UserQooHistory").IsClustered();

            builder.Property(x => x.HistorySeq).HasColumnName(@"HistorySeq").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.LoginId).HasColumnName(@"LoginId").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.QooHash).HasColumnName(@"QooHash").HasColumnType("nvarchar(max)").IsRequired(false);
        }
    }

}
// </auto-generated>
