// <auto-generated>
#nullable enable

using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Geo.Smart.AiAgentHub.DataAccess.Configuration
{
    public class VerifyCodeConfiguration : IEntityTypeConfiguration<VerifyCode>
    {
        public void Configure(EntityTypeBuilder<VerifyCode> builder)
        {
            builder.ToTable("VerifyCode", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_EnforceChangeQoo").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(128)").IsRequired().HasMaxLength(128);
            builder.Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.VerifyType).HasColumnName(@"VerifyType").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
