// <auto-generated>
#nullable enable

using Microsoft.AspNetCore.Http;

namespace Geo.Smart.AiAgentHub.DataAccess
{
    /// <summary>
    /// Main DbContext
    /// </summary>
    public partial class GdbContext : IdentityDbContext<ApplicationUser, ApplicationRole, string, ApplicationUserClaim, IdentityUserRole<string>, ApplicationUserLogin, ApplicationRoleClaim, ApplicationUserToken>, IGdbContext
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        /// <summary>
        /// 建構式
        /// </summary>
        public GdbContext(DbContextOptions<GdbContext> options,
            IHttpContextAccessor httpContextAccessor)
            : base(options)
        {
            _httpContextAccessor = httpContextAccessor;
            InitializePartial();
        }

        /// <summary>
        /// 建構式
        /// </summary>
        public GdbContext(DbContextOptions<GdbContext> options)
            : base(options)
        {
            InitializePartial();
        }

        public DbSet<AiProject> AiProjects { get; set; }
        public DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public DbSet<ApplicationRoleClaim> ApplicationRoleClaims { get; set; }
        public DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public DbSet<ApplicationUserClaim> ApplicationUserClaims { get; set; }
        public DbSet<ApplicationUserLogin> ApplicationUserLogins { get; set; }
        public DbSet<ApplicationUserToken> ApplicationUserTokens { get; set; }
        public DbSet<Captcha> Captchas { get; set; }
        public DbSet<Filex> Filexes { get; set; }
        public DbSet<LlmInfo> LlmInfoes { get; set; }
        public DbSet<McpServer> McpServers { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<Photo> Photos { get; set; }
        public DbSet<UserFootprint> UserFootprints { get; set; }
        public DbSet<UserHistory> UserHistories { get; set; }
        public DbSet<UserQooHistory> UserQooHistories { get; set; }
        public DbSet<UserTokenx> UserTokenxes { get; set; }
        public DbSet<VerifyCode> VerifyCodes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new AiProjectConfiguration());
            modelBuilder.ApplyConfiguration(new ApplicationRoleConfiguration());
            modelBuilder.ApplyConfiguration(new ApplicationRoleClaimConfiguration());
            modelBuilder.ApplyConfiguration(new ApplicationUserConfiguration());
            modelBuilder.ApplyConfiguration(new ApplicationUserClaimConfiguration());
            modelBuilder.ApplyConfiguration(new ApplicationUserLoginConfiguration());
            modelBuilder.ApplyConfiguration(new ApplicationUserTokenConfiguration());
            modelBuilder.ApplyConfiguration(new CaptchaConfiguration());
            modelBuilder.ApplyConfiguration(new FilexConfiguration());
            modelBuilder.ApplyConfiguration(new LlmInfoConfiguration());
            modelBuilder.ApplyConfiguration(new McpServerConfiguration());
            modelBuilder.ApplyConfiguration(new OrganizationConfiguration());
            modelBuilder.ApplyConfiguration(new PhotoConfiguration());
            modelBuilder.ApplyConfiguration(new UserFootprintConfiguration());
            modelBuilder.ApplyConfiguration(new UserHistoryConfiguration());
            modelBuilder.ApplyConfiguration(new UserQooHistoryConfiguration());
            modelBuilder.ApplyConfiguration(new UserTokenxConfiguration());
            modelBuilder.ApplyConfiguration(new VerifyCodeConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }


        partial void InitializePartial();
        partial void DisposePartial(bool disposing);
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
        static partial void OnCreateModelPartial(ModelBuilder modelBuilder, string schema);
    }
}
// </auto-generated>
